"""Build/refresh docs/papers_index.md from the PDFs under papers/.

Usage: python scripts/index_papers.py [--refresh-metadata]

Scans papers/**/*.pdf. The Tier column is the paper's top-level folder under
papers/ (e.g. tier1_neighbors), blank for PDFs directly in papers/, and is
always refreshed from where the file currently sits.

Reads only PDF document metadata (Info dict / XMP) and front-matter text on
page 1 (largest-font title, arXiv stamp, venue banner). Fields that cannot be
found confidently are left blank. Nothing beyond front matter is extracted.

Idempotent: rows are keyed by filename (not path), so moving a PDF between
tier folders keeps its row and notes. The manual columns ("What they did",
"What they could not do", "How ASB differs") are never overwritten. Existing
non-empty metadata cells are kept unless --refresh-metadata is passed, so
hand corrections survive re-runs. Rows for PDFs no longer in papers/ are kept
if any manual column has text, otherwise dropped. Content outside the
BEGIN/END markers in the index file is preserved.
"""

from __future__ import annotations

import argparse
import math
import re
from pathlib import Path

from pypdf import PdfReader

ROOT = Path(__file__).resolve().parent.parent
PAPERS_DIR = ROOT / "papers"
INDEX_PATH = ROOT / "docs" / "papers_index.md"

AUTO_COLS = ["Filename", "Tier", "Title", "Authors", "Year", "Venue"]
MANUAL_COLS = ["What they did", "What they could not do", "How ASB differs"]
COLUMNS = AUTO_COLS + MANUAL_COLS

BEGIN = "<!-- papers-index:begin (generated by scripts/index_papers.py) -->"
END = "<!-- papers-index:end -->"
DEFAULT_PREAMBLE = (
    "# Papers index\n\n"
    "Generated from `papers/**/*.pdf` by `scripts/index_papers.py`. Metadata is "
    "extracted from PDF front matter only; blank means not confidently found. "
    "The last three columns are written by hand and are never overwritten.\n\n"
)

ARXIV_STAMP = re.compile(
    r"arXiv:(\d{4}\.\d{4,5})(v\d+)?\s*\[[^\]]+\]\s*\d{1,2}\s+[A-Z][a-z]{2}\s+((?:19|20)\d{2})"
)
# Venue banners, matched against single first-page lines; group 1 is the venue.
# Each must contain a year, otherwise the match is not trusted.
VENUE_PATTERNS = [
    re.compile(r"^Published as an? (?:conference|workshop) paper at (?:the )?(.+)$"),
    re.compile(r"^(?:To appear|Accepted|Presented) (?:at|in|to|by) (?:the )?(.+)$"),
    re.compile(r"^(Proceedings of the .+)$"),
]
YEAR = re.compile(r"(?:19|20)\d{2}")
JUNK_TITLE = re.compile(r"^(untitled|microsoft word|document\d*|paper|main|arxiv)\b|\.(pdf|docx?|tex|dvi)$", re.I)


def clean(s: str | None) -> str:
    return re.sub(r"\s+", " ", s or "").strip()


def plausible_title(s: str) -> bool:
    return 8 <= len(s) <= 300 and not JUNK_TITLE.search(s) and not ARXIV_STAMP.search(s)


def respace(title: str, hint: str) -> str:
    """Restore word gaps lost in extraction, using `hint` (e.g. the filename)
    only when it has exactly the same letters/digits as `title`."""
    norm = lambda s: re.sub(r"[^0-9a-z]", "", s.lower())
    if not norm(title) or norm(title) != norm(hint):
        return title
    breaks, k = set(), 0
    for i, c in enumerate(hint):
        if c.isalnum():
            k += 1
        elif c.isspace() and k:
            breaks.add(k)
    out, k = [], 0
    for i, c in enumerate(title):
        out.append(c)
        if c.isalnum():
            k += 1
            nxt = title[i + 1] if i + 1 < len(title) else " "
            if k in breaks and not nxt.isspace():
                out.append(" ")
    return clean("".join(out))


def largest_font_text(page, plain: str) -> str:
    """Title = the text on the baselines that carry the page's largest font.

    Runs on those baselines are matched back to lines of the plain extraction
    (which has correct word spacing); small-caps titles mix two font sizes, so
    matching is done on the whitespace-free character sequence. Returns "" if
    the match is not exact.
    """
    runs: list[tuple[float, float, str]] = []

    def visitor(text, cm, tm, font_dict, font_size):
        if not text.strip():
            return
        # Skip rotated text (e.g. the arXiv sidebar stamp).
        if abs(tm[1]) > 1e-3 or abs(tm[2]) > 1e-3 or abs(cm[1]) > 1e-3 or abs(cm[2]) > 1e-3:
            return
        size = font_size * math.hypot(tm[2], tm[3]) * math.hypot(cm[2], cm[3])
        if size <= 0:
            size = font_size * abs(tm[3] or 1) * abs(cm[3] or 1)
        runs.append((round(size, 1), round(tm[5] * cm[3] + cm[5], 1), text))

    page.extract_text(visitor_text=visitor)
    if not runs:
        return ""
    top = max(size for size, _, _ in runs)
    baselines = {y for size, y, _ in runs if size >= top - 0.5}
    sig = re.sub(r"\s+", "", "".join(t for size, y, t in runs if y in baselines and size >= 0.6 * top))
    if not sig:
        return ""

    lines = [l.strip() for l in plain.splitlines() if l.strip()]
    for start in range(len(lines)):
        acc, picked = "", []
        for line in lines[start:]:
            acc += re.sub(r"\s+", "", line)
            if not sig.startswith(acc):
                break
            picked.append(line)
            if acc == sig:
                title = picked[0]
                for nxt in picked[1:]:  # undo LaTeX line-break hyphenation
                    title = title[:-1] + nxt if title.endswith("-") else f"{title} {nxt}"
                return clean(title)
    return ""


def extract(pdf: Path) -> dict[str, str]:
    out = {"Title": "", "Authors": "", "Year": "", "Venue": ""}
    try:
        reader = PdfReader(pdf)
    except Exception as exc:  # unreadable/encrypted PDFs keep blank fields
        print(f"warning: cannot open {pdf.name}: {exc}")
        return out

    info = reader.metadata or {}
    try:
        xmp = reader.xmp_metadata
    except Exception:
        xmp = None

    title = clean(info.get("/Title"))
    if not title and xmp is not None:
        title = clean((xmp.dc_title or {}).get("x-default"))
    authors = clean(info.get("/Author"))
    if not authors and xmp is not None and xmp.dc_creator:
        authors = "; ".join(clean(a) for a in xmp.dc_creator if clean(a))

    first = ""
    if reader.pages:
        page = reader.pages[0]
        try:
            first = page.extract_text() or ""
        except Exception:
            first = ""
        if not plausible_title(title):
            try:
                title = largest_font_text(page, first)
            except Exception:
                title = ""

    title = respace(title, pdf.stem)
    # A long run with no spaces means word gaps were lost; don't guess them.
    if any(len(w) > 30 for w in title.split()):
        title = ""
    out["Title"] = title if plausible_title(title) else ""
    out["Authors"] = authors if 2 <= len(authors) <= 500 else ""

    for line in first.splitlines()[:15]:  # banners sit at the top of page 1
        line = clean(line)
        for pat in VENUE_PATTERNS:
            m = pat.match(line)
            if m and YEAR.search(m.group(1)) and len(m.group(1)) <= 200:
                out["Venue"] = clean(m.group(1)).rstrip(".")
                out["Year"] = YEAR.findall(out["Venue"])[0]
                break
        if out["Venue"]:
            break
    # The arXiv stamp's date is the latest version's, not the publication year,
    # so it only supplies the arXiv ID as a venue, never a Year.
    stamp = ARXIV_STAMP.search(clean(first))
    if stamp and not out["Venue"]:
        out["Venue"] = f"arXiv:{stamp.group(1)}"
    return out


# --- markdown table I/O -------------------------------------------------------

def esc(s: str) -> str:
    return clean(s).replace("|", "\\|")


def split_row(line: str) -> list[str]:
    body = line.strip()
    if body.startswith("|"):
        body = body[1:]
    if body.endswith("|") and not body.endswith("\\|"):
        body = body[:-1]
    cells = re.split(r"(?<!\\)\|", body)
    return [c.strip().replace("\\|", "|") for c in cells]


def read_index(path: Path) -> tuple[str, str, dict[str, dict[str, str]]]:
    """Return (text before table, text after table, rows keyed by filename)."""
    if not path.exists():
        return DEFAULT_PREAMBLE, "", {}
    text = path.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        raise SystemExit(
            f"{path} exists but lacks the index markers; refusing to overwrite it. "
            f"Add '{BEGIN}' and '{END}' around the table, or move the file."
        )
    before, rest = text.split(BEGIN, 1)
    table, after = rest.split(END, 1)
    rows: dict[str, dict[str, str]] = {}
    lines = [l for l in table.splitlines() if l.strip().startswith("|")]
    if lines:
        header = split_row(lines[0])
        for line in lines[2:]:
            cells = split_row(line)
            row = {col: (cells[i] if i < len(cells) else "") for i, col in enumerate(header)}
            row = {c: row.get(c, "") for c in COLUMNS}
            if row["Filename"]:
                rows[row["Filename"]] = row
    return before, after, rows


def render(rows: list[dict[str, str]]) -> str:
    out = ["| " + " | ".join(COLUMNS) + " |", "|" + "|".join("---" for _ in COLUMNS) + "|"]
    for r in rows:
        out.append("| " + " | ".join(esc(r.get(c, "")) for c in COLUMNS) + " |")
    return "\n".join(out)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--refresh-metadata", action="store_true",
                    help="re-extract Title/Authors/Year/Venue even where cells are non-empty "
                         "(manual columns are still never touched)")
    args = ap.parse_args()

    before, after, existing = read_index(INDEX_PATH)
    pdfs = sorted(PAPERS_DIR.rglob("*.pdf"), key=lambda p: p.name.lower())

    merged: dict[str, dict[str, str]] = {}
    for pdf in pdfs:
        if pdf.name in merged:
            print(f"warning: duplicate filename {pdf.relative_to(PAPERS_DIR)}; skipping")
            continue
        found = extract(pdf)
        row = existing.get(pdf.name, {c: "" for c in COLUMNS})
        row["Filename"] = pdf.name
        rel = pdf.relative_to(PAPERS_DIR)
        row["Tier"] = rel.parts[0] if len(rel.parts) > 1 else ""
        for col, val in found.items():
            if args.refresh_metadata or not row.get(col):
                row[col] = val
        merged[pdf.name] = row

    for name, row in existing.items():
        if name not in merged and any(row.get(c) for c in MANUAL_COLS):
            print(f"note: {name} not in papers/ but has manual notes; keeping row")
            merged[name] = row

    rows = sorted(merged.values(), key=lambda r: r["Filename"].lower())
    INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    body = f"{before}{BEGIN}\n{render(rows)}\n{END}{after if after else chr(10)}"
    INDEX_PATH.write_text(body, encoding="utf-8", newline="\n")
    print(f"wrote {INDEX_PATH.relative_to(ROOT)} ({len(rows)} rows)")


if __name__ == "__main__":
    main()
